### ISSUE TITLE
Fatal error: Class 'PHPUnit_Framework_TestCase' not found ...

### ISSUE THREAD

**Issue by Salamek** [gopaycommunity/gopay-php-api#1]
# Error
When i install gopay-php-api wia composer:

```bash
composer require gopay/payments-sdk-php
```
And do simple scipt like:

```php
<?php

require_once "vendor/autoload.php";
```
And run it i get this error:
```
Fatal error: Class 'PHPUnit_Framework_TestCase' not found in vendor/gopay/payments-sdk-php/tests/remote/GivenGoPay.php on line 9
```

# Reason
This is because `composer.json` loads `tests/remote/GivenGoPay.php` for non-dev installation, but phpunit is installed only when dev is used.

# Fix

`tests/remote/GivenGoPay.php` should not be autoloaded at all it is test not something we need to run from our code

**Comment by zdenekdrahos** [comment]
Good catch, thanks!
Fixed in version 1.0.1
