### ISSUE TITLE
CURLOPT_FOLLOWLOCATION vs open_basedir

### ISSUE THREAD

**Issue by ETNyx88** [gopaycommunity/gopay-php-api#11]
Hello,

got this warning:
```
Warning: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /***/vendor/mashape/unirest-php/src/Unirest/Request.php on line 430
```
Open_basedir is pretty common on shared hosting. In fact this broke payment. Most ridiculous is that, it's look like we don't need this option set to TRUE, or not? What's optimal fix for this issue?

**Comment by jarred-cz** [comment]
Absolutely agree. What about using Guzzle?
