### ISSUE TITLE
composer guzzle 6

### ISSUE THREAD

**Issue by quidko** [gopaycommunity/gopay-php-api#15]
I have guzzle 6.3.0
may be you must use double pipe in composer.json 

    - Installation request for gopay/payments-sdk-php ^1.3 -> satisfiable by gopay/payments-sdk-php[v1.3.0].
    - gopay/payments-sdk-php v1.3.0 requires guzzlehttp/guzzle ~5.0 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by FSichinger** [comment]
outdated
