### ISSUE TITLE
GuzzleHttp\Handler\curl_reset() not supported in PHP 5.4

### ISSUE THREAD

**Issue by 1uba** [gopaycommunity/gopay-php-api#20]
`Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in ...`

**More details:**
https://stackoverflow.com/questions/25523004/fatal-error-curl-reset-undefined-why

**Comment by 1uba** [comment]
Temporarily solved by:

```
if (!function_exists('curl_reset'))
{
    function curl_reset(&$ch)
    {
        $ch = curl_init();
    }
}
```

**Comment by FSichinger** [comment]
When does this happen?

Travis tests against 5.4 as well without this kind of error.
