### ISSUE TITLE
Údaje o zákazníkovi

### ISSUE THREAD

**Issue by kironet** [gopaycommunity/gopay-php-api#22]
Dobrý den,

nevím kde jinde se zeptat, takže píšu sem.
Proč GoPay chce údaje o zákazníkovi při vytvoření platby(hlavně jméno, příjemní, adresa, telefon)? 
Ptám se kvůli GDPR a popř. jak to řešit. 

Díky

**Comment by FSichinger** [comment]
Dobrý den,

tyto předávat tyto údaje je nepovinné, více viz  dokumentace https://doc.gopay.com/cs/?lang=php# 

Ohledně GDPR situaci sledujeme a jakmile budeme mít více informací, tak případně upravíme integraci. 

Pro více informací a rychlejší odpověď bych doporučil Vaše dotazy směřovat spíše na naší zákaznickou/technickou podporu.
