### ISSUE TITLE
Payment refund returns curl error - timeout

### ISSUE THREAD

**Issue by jkavalik** [gopaycommunity/gopay-php-api#34]
When refunding payments in the test environment I sometimes get an error from ` $statusResult = $this->client->refundPayment($paymentId, round($entity->amount * 100));` -> `(string)$statusResult`
```
cURL error 28: Operation timed out after 30001 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
Subsequent payment status check shows the payment as REFUNDED.
Other operations seem to work fine and the refund call does too sometimes, but not always.

**Comment by gopayprovoz** [comment]
Hello,

Thanks for information. Could you please send us the ID of payment where you had this problem?
Please send us all this information via integrace@gopay.cz
