### ISSUE TITLE
Nefunkční neprodukční prostředí v Symfony 

### ISSUE THREAD

**Issue by Holicz** [gopaycommunity/gopay-php-api#36]
**Problém:** Při nastavení `isProductionMode` na `false` se použije produkční prostředí v novém Symfony, které používá `.env` na konfiguraci.

**Proč:** Ve třídě `GoPay` v metodě `buildUrl()` na řádku `49` se používá `(bool)$this->getConfig('isProductionMode')`. To je v novém symfony problém, protože parametry z `.env` souboru jsou by default přetypovány na string a `(bool) 'false'` vrací `true`. Samozřejmě programátor může pole přetypovat, ale není to moc typické a v Symfony dokumentaci je to docela utopené.

**Řešení:** Předělat funkci `buildUrl` například takto. Pravděpodobně se najde i hezčí řešení.
```php
public function buildUrl($urlPath)
    {
        $isProductionMode = $this->getConfig('isProductionMode');
        if (!(bool) $isProductionMode || $isProductionMode === 'false') {
            return 'https://gw.sandbox.gopay.com/';
        } 
        
        return 'https://gate.gopay.cz/';
    }
```

**Comment by FSichinger** [comment]
Upraveno v v1.4.3, 

viz  2860806 

Knihovna momentalne dokáže zpracovat uvedene hodnoty
