### ISSUE TITLE
Super ❤

### ISSUE THREAD

**Issue by mzvarik** [gopaycommunity/gopay-php-api#37]
**Krásná dokumentace i třída... velmi chválím!**
Vše funguje jak má!
Toto opravdu není zvykem 👍 ❤

**Comment by gopayprovoz** [comment]
Dobrý den,
 
 děkujeme, vážíme si vaší zpětné vazby.
 V případě dotazů mě kdykoliv kontaktujte. 
 S pozdravem

 
 <https://www.gopay.com/cs?utm_source=email&utm_medium=signature&utm_campaign=tomas-holub> 
 
 Tomáš Holub • Technická podpora
 <tel:00420> • integrace@gopay.cz <mailto:integrace@gopay.cz> 
 www.gopay.com <https://www.gopay.com/cs?utm_source=email&utm_medium=signature&utm_campaign=tomas-holub> 
 Sledujte nás: <https://www.facebook.com/gopay.cz> <https://twitter.com/gopaycz> <https://www.linkedin.com/company/gopay-s-r-o-> 
 
 Čtěte náš blog <http://blog.gopay.com/?utm_source=email&utm_medium=signature&utm_campaign=tomas-holub> <http://blog.gopay.com/?utm_source=email&utm_medium=signature&utm_campaign=tomas-holub> 
 
 
----------------------
 Dne 24.7.2020 v 22:02:02
