### ISSUE TITLE
Test URL doesn't work anymore

### ISSUE THREAD

**Issue by hubipe** [gopaycommunity/gopay-php-api#5]
The test URL (https://github.com/gopaycommunity/gopay-php-api/blob/35fd946162a0e29562e15cc6d6995289824a8a9d/src/GoPay.php#L45) has changed by commit 35fd946162a0e29562e15cc6d6995289824a8a9d to (probably) internal URL. Thus when trying to send test payment, API returns HTTP 500: Could not resolve host: gopay-gw.

**Comment by EdgedesignCommon** [comment]
Thank you for reporting this to us. Fixed with https://github.com/gopaycommunity/gopay-php-api/pull/7
